---

- hosts: jiras
  become: yes
  # NB: this is overridden in several tasks
  become_user: root
  roles:
    - oraclejdk8
    - repos/mysql56
    - mysql56
    - jira
    - jiradb
    - postinstall
