---

- name: apology
  debug:
    msg: i cannot legally ship oracle jdk8. checking for presence

- name: check java version
  command: "{{ java8_home }}/bin/java -version"
  register: javaver

- name: check output for things that look like Oracle JDK8
  when: '"{{ item }}" not in javaver.stderr'
  fail:
    msg: "java -version gave: {{ javaver.stderr }}"
  with_items:
    - Java HotSpot
    - 1.8.
    - Java(TM)
