---

- name: install MySQL-python
  yum: name=MySQL-python state=present

- name: create jira db
  mysql_db: name={{ jira_dbname }}
            encoding=utf8

- name: create jira db account
  mysql_user: name={{ jira_dbuser }}
              password={{ jira_dbpass }}
              priv={{ jira_dbname }}.*:ALL
              host={{ item }} state=present
  with_items:
    - '%'
    - 'localhost'
